"""Render project-owned field metadata, inactive rules, permission set and dictionary.

No Salesforce session is required. XML validation locally does not prove that an
org accepts a deployment; the Salesforce Metadata API is the deployment authority.
"""

import argparse
from pathlib import Path
from xml.etree import ElementTree as ET

from gtmdq.config import PROJECT_ROOT, read_yaml

NS = "http://soap.sforce.com/2006/04/metadata"
BASE = Path("force-app/main/default")


def node(parent: ET.Element, name: str, text: object) -> ET.Element:
    child = ET.SubElement(parent, name)
    child.text = str(text).lower() if isinstance(text, bool) else str(text)
    return child


def xml(root: ET.Element) -> str:
    ET.indent(root, space="    ")
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(root, encoding="unicode") + "\n"


def field_xml(field: dict, schema: dict) -> str:
    root = ET.Element("CustomField", xmlns=NS)
    node(root, "fullName", field["name"])
    if field.get("external"):
        node(root, "caseSensitive", True)
    if field["type"] == "Lookup":
        node(root, "deleteConstraint", "SetNull")
    node(root, "description", f"GTM DQ: {field['label']}. See the project data dictionary.")
    if field.get("external"):
        node(root, "externalId", True)
    node(root, "label", field["label"])
    if "length" in field:
        node(root, "length", field["length"])
    if "precision" in field:
        node(root, "precision", field["precision"])
    if field["type"] == "Lookup":
        node(root, "referenceTo", field["reference"])
        node(root, "relationshipLabel", "Data Quality Issues")
        node(root, "relationshipName", "GTM_Data_Quality_Issues")
    node(root, "required", False)
    if "scale" in field:
        node(root, "scale", field["scale"])
    node(root, "type", field["type"])
    if field.get("external"):
        node(root, "unique", True)
    if field["type"] == "Picklist":
        values = field["values"]
        if isinstance(values, str):
            values = schema["picklists"][values]
        value_set = ET.SubElement(root, "valueSet")
        node(value_set, "restricted", True)
        definition = ET.SubElement(value_set, "valueSetDefinition")
        node(definition, "sorted", False)
        for value in values:
            option = ET.SubElement(definition, "value")
            node(option, "fullName", value)
            node(option, "default", False)
            node(option, "label", value)
    return xml(root)


def render() -> dict[Path, str]:
    schema = read_yaml(PROJECT_ROOT / "config/salesforce_schema.yml")
    outputs: dict[Path, str] = {}
    permissions = ET.Element("PermissionSet", xmlns=NS)
    node(permissions, "description", "Edit project DQ fields and review issues; no delete access.")
    fields_by_object = {}
    dictionary = [
        "# Salesforce custom field dictionary",
        "",
        "Generated by `scripts/build_metadata.py` from `config/salesforce_schema.yml`.",
        "All fields are optional at schema level so dirty source data can be studied.",
        "External IDs are unique and case-sensitive. Validation rules are initially inactive.",
        "Standard/source-field mappings are documented in [generation.md](generation.md).",
        "",
        "| Object | Field | API Name | Data Type | Definition | Required? | System of Record | "
        "Source | Validation Rule | Example | Business Owner |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for obj, extra_fields in schema["objects"].items():
        fields = extra_fields if obj == "Data_Quality_Issue__c" else schema["common"] + extra_fields
        fields_by_object[obj] = fields
        for field in fields:
            relative = BASE / "objects" / obj / "fields" / f"{field['name']}.field-meta.xml"
            outputs[relative] = field_xml(field, schema)
            entry = ET.SubElement(permissions, "fieldPermissions")
            node(entry, "editable", True)
            node(entry, "field", f"{obj}.{field['name']}")
            node(entry, "readable", True)
            dtype = field["type"]
            example = ""
            validation = ""
            if "length" in field:
                dtype += f"({field['length']})"
            if "precision" in field:
                dtype += f"({field['precision']},{field['scale']})"
            if "values" in field:
                values = field["values"]
                if isinstance(values, str):
                    values = schema["picklists"][values]
                example = values[0]
                validation = "Allowed: " + ", ".join(values)
            if field.get("external"):
                validation = "Unique external ID"
                example = "SYN-A-000001" if obj != "Data_Quality_Issue__c" else "rule:entity-key"
            if field["type"] == "Lookup":
                validation = f"Existing {field['reference']} ID"
            derived = field["name"].startswith("DQ_") or obj == "Data_Quality_Issue__c"
            source = "DQ engine (planned)" if derived else "Synthetic source"
            dictionary.append(
                f"| {obj} | {field['label']} | `{field['name']}` | {dtype} | "
                f"{definition(field['name'], field['label'])} | No | "
                f"{'DQ results' if derived else 'Salesforce'} | {source} | "
                f"{validation} | {example} | Revenue Operations |"
            )
    node(permissions, "hasActivationRequired", False)
    node(permissions, "label", "GTM DQ Operator")
    for obj in fields_by_object:
        entry = ET.SubElement(permissions, "objectPermissions")
        for key, value in (
            ("allowCreate", True),
            ("allowDelete", False),
            ("allowEdit", True),
            ("allowRead", True),
            ("modifyAllRecords", False),
            ("object", obj),
            ("viewAllRecords", False),
        ):
            node(entry, key, value)
    outputs[BASE / "permissionsets/GTMDQ_Operator.permissionset-meta.xml"] = xml(permissions)
    issue = ET.Element("CustomObject", xmlns=NS)
    node(issue, "deploymentStatus", "Deployed")
    node(issue, "description", "Human-reviewed, prioritized data quality findings.")
    node(issue, "enableActivities", False)
    node(issue, "enableReports", True)
    node(issue, "label", "Data Quality Issue")
    name = ET.SubElement(issue, "nameField")
    node(name, "displayFormat", "DQI-{00000}")
    node(name, "label", "Data Quality Issue Number")
    node(name, "type", "AutoNumber")
    node(issue, "pluralLabel", "Data Quality Issues")
    node(issue, "sharingModel", "ReadWrite")
    outputs[BASE / "objects/Data_Quality_Issue__c/Data_Quality_Issue__c.object-meta.xml"] = xml(
        issue
    )
    rules = [
        (
            "Account",
            "Enterprise_Requires_Website",
            'AND(ISPICKVAL(Segment__c, "Enterprise"), ISBLANK(Website))',
            "Enterprise Accounts require a Website.",
            "Website",
        ),
        (
            "Contact",
            "Contact_Requires_Account",
            "ISBLANK(AccountId)",
            "Associate this Contact with an Account.",
            "AccountId",
        ),
        (
            "Opportunity",
            "Open_Opportunity_Close_Date",
            "AND(NOT(IsClosed), CloseDate < TODAY())",
            "Open Opportunities require a current or future Close Date.",
            "CloseDate",
        ),
    ]
    for obj, name, formula, message, field in rules:
        root = ET.Element("ValidationRule", xmlns=NS)
        node(root, "fullName", name)
        node(root, "active", False)
        node(
            root, "description", "Activate only after baseline dirty data is loaded and evaluated."
        )
        node(root, "errorConditionFormula", formula)
        node(root, "errorDisplayField", field)
        node(root, "errorMessage", message)
        outputs[BASE / "objects" / obj / "validationRules" / f"{name}.validationRule-meta.xml"] = (
            xml(root)
        )
    outputs[Path("docs/data_dictionary.md")] = "\n".join(dictionary) + "\n"
    return outputs


def definition(name: str, label: str) -> str:
    return {
        "External_Source_Id__c": "Stable synthetic identity used for idempotent upserts.",
        "External_Issue_Key__c": (
            "Stable rule/entity issue identity across runs; never an auto-number."
        ),
        "Run_Id__c": "Most recent detection run UUID.",
        "DQ_Score__c": "Applicable-check weighted score, 0 to 100.",
        "DQ_Status__c": "Quality status with severity override.",
        "DQ_Issue_Count__c": "Active findings on this entity in the latest run.",
        "Canonical_Domain__c": (
            "Normalized domain without scheme, www prefix, path or trailing slash."
        ),
        "Ingestion_Batch_Id__c": "Synthetic source batch lineage; not a DQ run ID.",
        "Priority_Score__c": "Demo remediation priority from 0 to 100.",
        "Detection_Confidence__c": "Detection confidence expressed on a 0 to 1 scale.",
        "Pipeline_At_Risk__c": "Open opportunity exposure; issue rows must not be summed globally.",
        "Status__c": "Human workflow state; reruns must preserve review decisions.",
    }.get(name, f"{label} as defined in the project specification.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    drift = []
    for relative, content in render().items():
        path = PROJECT_ROOT / relative
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                drift.append(str(relative))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if drift:
        raise SystemExit("Generated metadata differs: " + ", ".join(drift))
    print(
        "Metadata is current." if args.check else "Generated metadata and custom field dictionary."
    )


if __name__ == "__main__":
    main()
